name: Merge PR

on:
  pull_request:
    types: [closed]

jobs:
  pr-job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Message
        run: echo "PR mergÃ©e ğŸ‰"
